ALTER TABLE products ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE services ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE staff ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE customers ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE branches ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE subscription_plans ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE coupons ADD COLUMN deleted_at TIMESTAMP NULL;
ALTER TABLE gift_cards ADD COLUMN deleted_at TIMESTAMP NULL;
