import { useAuthStore } from '../../store/useAuthStore';
import { useStaffPayrollQuery } from '../../hooks/api/usePayroll';

import { EmptyState } from '../../components/ui/EmptyState';

export const Payroll = () => {
  const { user } = useAuthStore();
  const staffId = user?.staffId;

  const { data: response, isLoading } = useStaffPayrollQuery(staffId);

  return (
    <>
<div className="mb-8">
        <h2 className="font-display-lg text-[32px] text-on-surface mb-2">My Payroll</h2>
        <p className="text-on-surface-variant text-body-lg">View your earnings, commissions, and payroll history.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="glass-panel p-6 rounded-[24px]">
          <h3 className="font-label-md text-on-surface-variant uppercase tracking-wider mb-2">Total Earnings (YTD)</h3>
          <p className="font-display-md text-[36px] text-primary">
            ${response?.content?.reduce((acc: number, curr: any) => acc + curr.totalAmount, 0).toFixed(2) || '0.00'}
          </p>
        </div>
        <div className="glass-panel p-6 rounded-[24px]">
          <h3 className="font-label-md text-on-surface-variant uppercase tracking-wider mb-2">Total Commissions</h3>
          <p className="font-display-md text-[36px] text-on-surface">
            ${response?.content?.reduce((acc: number, curr: any) => acc + curr.commissionAmount, 0).toFixed(2) || '0.00'}
          </p>
        </div>
        <div className="glass-panel p-6 rounded-[24px]">
          <h3 className="font-label-md text-on-surface-variant uppercase tracking-wider mb-2">Latest Payout</h3>
          <p className="font-display-md text-[36px] text-on-surface">
            ${response?.content?.[0]?.totalAmount?.toFixed(2) || '0.00'}
          </p>
        </div>
      </div>

      <div className="glass-panel overflow-hidden rounded-[24px]">
        <div className="p-6 border-b border-outline-variant">
          <h3 className="font-display-sm text-[24px] text-on-surface">Payroll History</h3>
        </div>

        {isLoading ? (
          <div className="p-6 space-y-4 animate-pulse">
            {[1,2,3].map(i => (
              <div key={i} className="h-16 bg-surface-container rounded-xl"></div>
            ))}
          </div>
        ) : !response?.content?.length ? (
          <EmptyState 
            icon="account_balance_wallet"
            title="No payroll records found"
            description="Your payroll history will appear here once generated by admin."
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-outline-variant bg-surface-container-lowest/50">
                  <th className="p-4 font-label-md text-on-surface-variant font-medium">Period</th>
                  <th className="p-4 font-label-md text-on-surface-variant font-medium text-right">Base Salary</th>
                  <th className="p-4 font-label-md text-on-surface-variant font-medium text-right">Commissions</th>
                  <th className="p-4 font-label-md text-on-surface-variant font-medium text-right">Deductions</th>
                  <th className="p-4 font-label-md text-on-surface-variant font-medium text-right">Total</th>
                  <th className="p-4 font-label-md text-on-surface-variant font-medium text-right">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-outline-variant">
                {response.content.map((record: any) => (
                  <tr key={record.id} className="hover:bg-surface-container-lowest/50 transition-colors">
                    <td className="p-4">
                      <p className="font-headline-sm text-on-surface">
                        {new Date(record.periodStart).toLocaleDateString()} - {new Date(record.periodEnd).toLocaleDateString()}
                      </p>
                    </td>
                    <td className="p-4 text-right text-on-surface-variant font-body-md">${record.baseSalary?.toFixed(2)}</td>
                    <td className="p-4 text-right text-success font-body-md">+${record.commissionAmount?.toFixed(2)}</td>
                    <td className="p-4 text-right text-error font-body-md">-${record.deductionAmount?.toFixed(2)}</td>
                    <td className="p-4 text-right font-headline-sm text-on-surface">${record.totalAmount?.toFixed(2)}</td>
                    <td className="p-4 text-right">
                      <span className={`status-pill ${record.status === 'PAID' ? 'success' : 'warning'}`}>
                        {record.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </>
  );
};
